BOARD_TAG    = uno
AVRDUDE_ARD_BAUDRATE = 57600
ARDUINO_PORT = /dev/tty.SLAB_USBtoUART

ARDUINO_DIR   = /Applications/Arduino2.app/Contents/Java

# normally ISP_PROG is defined BOARD_TAG config entries in boards.txt
#ISP_PROG = -c usbasp -B 32


ARDUINO_LIBS = EEPROM
include ~/src/Arduino/arduino-mk/Arduino.mk

